# Generated by Django 2.0.7 on 2018-07-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('info', models.TextField(verbose_name='Описание ресурса')),
                ('condition_text', models.TextField(verbose_name='Описание условия сбора ресурса')),
                ('condition', models.TextField(verbose_name='условия сбора ресурса')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
    ]
