# Generated by Django 2.0.7 on 2018-07-23 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_miner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_miner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория ресурса',
                'verbose_name_plural': 'Категории ресурсов',
            },
        ),
        migrations.AddField(
            model_name='miner',
            name='level',
            field=models.TextField(null=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='miner',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Category_miner', verbose_name='Категория ресурса'),
        ),
    ]
