# Generated by Django 2.1 on 2018-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180723_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_item', models.IntegerField(default=0)),
                ('item_name', models.CharField(max_length=64, verbose_name='Название')),
                ('item_desc', models.TextField(verbose_name='Описание предмета')),
                ('options', models.TextField(verbose_name='характеристики')),
                ('type_slot', models.CharField(max_length=64, verbose_name='номер слота')),
                ('item_type', models.CharField(max_length=64, verbose_name='тип предмета')),
            ],
            options={
                'verbose_name': 'База Предметов',
                'verbose_name_plural': 'База Предметов',
            },
        ),
    ]
