# Generated by Django 2.1 on 2018-08-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_baseitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitems',
            name='type_slot',
            field=models.CharField(choices=[('шлем', '1'), ('торс', '2'), ('левая рука', '3'), ('правая рука', '4'), ('перчатки', '5'), ('Штаны', '6'), ('боты', '7'), ('пояс', '8'), ('сумка', '9')], default=1, max_length=64, verbose_name='номер слота'),
        ),
    ]
