# Generated by Django 2.1 on 2018-08-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180812_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitems',
            name='item_type',
            field=models.CharField(choices=[('cloth', 'cloth'), ('chainmail', 'chainmail'), ('plate', 'plate')], default='cloth', max_length=32, verbose_name='тип предмета'),
        ),
        migrations.AlterField(
            model_name='baseitems',
            name='type_slot',
            field=models.CharField(choices=[('1', '1_шлем'), ('2', '2_торс'), ('3', '3_левая рука'), ('4', '4_правая рука'), ('5', '5_перчатки'), ('6', '6_Штаны'), ('7', '7_боты'), ('8', '8_пояс'), ('9', '9_сумка')], default=1, max_length=64, verbose_name='номер слота'),
        ),
    ]
