# Generated by Django 2.1 on 2018-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20180812_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseitems',
            name='item_type',
            field=models.CharField(choices=[('cloth', 'cloth'), ('chainmail', 'chainmail'), ('plate', 'plate'), ('tool', 'tool'), ('resource', 'resource')], default='cloth', max_length=32, verbose_name='тип предмета'),
        ),
    ]
