# Generated by Django 2.1 on 2018-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_inventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Инвентарь игроков', 'verbose_name_plural': 'Инвентарь игроков'},
        ),
        migrations.AlterField(
            model_name='baseitems',
            name='item_type',
            field=models.CharField(choices=[('cloth', 'ткань'), ('chainmail', 'кольчуга'), ('plate', 'латы'), ('tool', 'инструменты'), ('resource', 'ресурсы')], default='cloth', max_length=32, verbose_name='тип предмета'),
        ),
    ]
