# Generated by Django 2.1 on 2018-08-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180812_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='slot',
            field=models.IntegerField(choices=[(8, '8_пояс'), (9, '9_сумка')], default=9),
        ),
    ]
