# Generated by Django 2.1 on 2018-08-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180812_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_qrcore', models.CharField(max_length=64)),
                ('lastupdate', models.DateTimeField(auto_now_add=True)),
                ('resource_type', models.CharField(choices=[('herb', 'трава'), ('ore', 'руда'), ('wool', 'шерсть')], default='herb', max_length=12)),
            ],
            options={
                'verbose_name_plural': 'база QR кодов',
                'verbose_name': 'база QR кодов',
            },
        ),
    ]
