# Generated by Django 2.1 on 2018-08-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_qrcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QrCode',
            new_name='BaseQrCode',
        ),
    ]
