# Generated by Django 2.1 on 2018-08-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20180812_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseqrcode',
            name='id_qrcore',
            field=models.CharField(max_length=64, verbose_name='Id QR code'),
        ),
    ]
