# Generated by Django 2.1 on 2018-08-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20180812_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miner',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category_miner',
        ),
        migrations.DeleteModel(
            name='Miner',
        ),
    ]
